variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_key_name" {}
variable "aws_key_path" {}
variable "vpc_name" {}
variable "network_prefix" {}
variable "aws_region" {}
variable "az" {}
variable "subnet-priv_cidr" {}
variable "subnet-pub_cidr" {}
variable "rhel_ami" {}
