variable "mod_aws_access_key" {}
variable "mod_aws_secret_key" {}
variable "mod_aws_key_name" {}
variable "mod_aws_key_path" {}
variable "mod_vpc_name" {}
variable "mod_network_prefix" {}
variable "mod_aws_region" {}
variable "mod_az" {}
variable "mod_subnet-private_cidr" {}
variable "mod_subnet-public_cidr" {}
variable "mod_rhel_ami" {}
